### ISSUE TITLE
sonos party_mode fails to group 3 speakers

### ISSUE THREAD

**Issue by mprudhom** [gotwalt/sonos#46]
On OS 10.9 (ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin13]) and 3 Sonos devices (Play 1, Playbar, and Play 3):

```
08:59 ~$ sonos devices
BRIDGE              10.0.1.100
Kitchen             10.0.1.119
Living Room         10.0.1.101
Dining Room         10.0.1.104
```

Party mode seems to always group 2 of them, but fails to group the third and gives an error:

```
08:59 ~$ sonos party_mode
/Library/Ruby/Gems/2.0.0/gems/savon-2.7.2/lib/savon/response.rb:85:in `raise_soap_and_http_errors!': (s:Client) UPnPError (Savon::SOAPFault)
	from /Library/Ruby/Gems/2.0.0/gems/savon-2.7.2/lib/savon/response.rb:14:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/savon-2.7.2/lib/savon/operation.rb:64:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/savon-2.7.2/lib/savon/operation.rb:64:in `create_response'
	from /Library/Ruby/Gems/2.0.0/gems/savon-2.7.2/lib/savon/operation.rb:55:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/savon-2.7.2/lib/savon/client.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/sonos-0.3.6/lib/sonos/endpoint/a_v_transport.rb:262:in `send_transport_message'
	from /Library/Ruby/Gems/2.0.0/gems/sonos-0.3.6/lib/sonos/endpoint/a_v_transport.rb:252:in `set_av_transport_uri'
	from /Library/Ruby/Gems/2.0.0/gems/sonos-0.3.6/lib/sonos/endpoint/a_v_transport.rb:220:in `join'
	from /Library/Ruby/Gems/2.0.0/gems/sonos-0.3.6/lib/sonos/system.rb:43:in `block in party_mode'
	from /Library/Ruby/Gems/2.0.0/gems/sonos-0.3.6/lib/sonos/system.rb:41:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/sonos-0.3.6/lib/sonos/system.rb:41:in `party_mode'
	from /Library/Ruby/Gems/2.0.0/gems/sonos-0.3.6/lib/sonos/cli.rb:32:in `party_mode'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/sonos-0.3.6/bin/sonos:7:in `<top (required)>'
	from /usr/bin/sonos:23:in `load'
	from /usr/bin/sonos:23:in `<main>'
```

**Comment by jsgoecke** [comment]
I am getting the same thing:

```
irb(main):013:0> system.party_mode
Savon::SOAPFault: (s:Client) UPnPError
	from /usr/local/lib/ruby/gems/2.2.0/gems/savon-2.11.1/lib/savon/response.rb:85:in `raise_soap_and_http_errors!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/savon-2.11.1/lib/savon/response.rb:14:in `initialize'
	from /usr/local/lib/ruby/gems/2.2.0/gems/savon-2.11.1/lib/savon/operation.rb:72:in `new'
	from /usr/local/lib/ruby/gems/2.2.0/gems/savon-2.11.1/lib/savon/operation.rb:72:in `create_response'
	from /usr/local/lib/ruby/gems/2.2.0/gems/savon-2.11.1/lib/savon/operation.rb:58:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/savon-2.11.1/lib/savon/client.rb:36:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/sonos-0.3.6/lib/sonos/endpoint/a_v_transport.rb:262:in `send_transport_message'
	from /usr/local/lib/ruby/gems/2.2.0/gems/sonos-0.3.6/lib/sonos/endpoint/a_v_transport.rb:252:in `set_av_transport_uri'
	from /usr/local/lib/ruby/gems/2.2.0/gems/sonos-0.3.6/lib/sonos/endpoint/a_v_transport.rb:220:in `join'
	from /usr/local/lib/ruby/gems/2.2.0/gems/sonos-0.3.6/lib/sonos/system.rb:43:in `block in party_mode'
	from /usr/local/lib/ruby/gems/2.2.0/gems/sonos-0.3.6/lib/sonos/system.rb:41:in `each'
	from /usr/local/lib/ruby/gems/2.2.0/gems/sonos-0.3.6/lib/sonos/system.rb:41:in `party_mode'
	from (irb):13
	from /usr/local/bin/irb:11:in `<main>'
```
